apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m5m3n429d-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m5m3n429d-nodejs 
  name: m5m3n429d-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: m5m3n429d-nodejs 
